name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install ssh-agent
      run: eval "$(ssh-agent -s)"

    - name: Add SSH private key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
            -i <(echo "${{ secrets.SSH_PRIVATE_KEY }}") \
            ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} 'bash -s' < deploy.sh
